public_unitinsurancepolicy_index:
    path:     /links
    defaults: { _controller: "HVGPublicBundle:UnitInsurancePolicy:index" }
    methods:  GET

public_unitinsurancepolicy_new:
    path:     /{hash}/new
    defaults: { _controller: "HVGPublicBundle:UnitInsurancePolicy:new" }
    methods:  [GET, POST]
