accesscontrol_guest_links:
    path:     /links
    defaults: { _controller: "HVGAccessControlBundle:Guest:links" }
    methods:  GET

accesscontrol_guest_index:
    path:     /index
    defaults: { _controller: "HVGAccessControlBundle:Guest:index" }
    methods:  GET

accesscontrol_guest_test:
    path:     /test
    defaults: { _controller: "HVGAccessControlBundle:Guest:test" }
    methods:  GET

accesscontrol_guest_search_residents:
    path:     /searchresidents
    defaults: { _controller: "HVGAccessControlBundle:Guest:searchResidents" }
    methods:  GET

accesscontrol_guest_search_person:
    path:     /searchperson
    defaults: { _controller: "HVGAccessControlBundle:Guest:searchPerson" }
    methods:  GET

accesscontrol_guest_new:
    path:     /{hash}/{accessgate}/{accessguard}/{unitgroup}/{unit}/new
    defaults: { _controller: "HVGAccessControlBundle:Guest:new" }
    methods:  [GET, POST]
