imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: framework.yml }
    - { resource: doctrine.yml }
    - { resource: twig.yml }
    - { resource: stof_doctrine_extensions.yml }
    - { resource: swiftmailer.yml }
    - { resource: assetic.yml }
    - { resource: knp_menu.yml }
    - { resource: knp_paginator.yml }
    - { resource: braincrafted.yml }
    - { resource: vich_uploader.yml }
    - { resource: liip_imagine.yml }
    - { resource: fos_user.yml }
#    - { resource: stfalcon_tinymce.yml }
#    - { resource: oneup_uploader.yml }
#    - { resource: "@AdminBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: es
    roles:
        ROLE_AGENT: Agente
        ROLE_ADMIN: Administrador
        ROLE_SUPER_ADMIN: Administrador de Sistema
    petgroups:
        1: Canino
        2: Felino
        3: Ave
        4: Pez
        5: Exótico
    petgenders:
        m: Macho
        h: Hembra
        c: Macho Castrado
        e: Hembra Esterilizada
        s: Sin sexar
    petcolors:
        1: Blanco, Perla, Marfil
        2: Negro, Ébano, Grafito, Azabache
        3: Gris, Acero, Plomo, Humo, Ceniza, Isabela, Sal pimienta, Azul, Lila, Lavanda, Plateado, Plata
        4: Crema, Barquillo, Arena, Beige, Cervato
        5: Amarillo, Anaranjado, Fuego, Naranjo, Dorado, Limón, Albaricoque, Paja, Rubio, Oro
        6: Café, Marrón, Castaño, Cebellina, Avellana, Chocolate, Pardo, Sepia, Foca, Canela, Caramelo, Ocre
        7: Rojo, Caoba, Alazan, Óxido, Cobre, Carmesí, Burdeo, Carmín
    ticketstatuses:
        1: Nuevo
        2: Asignado
        3: En Progreso
        4: Pendiente
        5: Resuelto
        6: Cerrado