liip_imagine:
    resolvers:
        default:
            web_path: ~
    filter_sets:
        cache: ~
        logo_login:
            quality: 75
            filters:
                upscale: { min: [800, 900] }
                thumbnail: { size: [800, 900], mode: outbound }
        logo_small:
            quality: 75
            filters:
                upscale: { min: [300, 80] }
                thumbnail: { size: [300, 80], mode: inset }
        logo_medium:
            quality: 75
            filters:
                upscale: { min: [600, 160] }
                thumbnail: { size: [600, 160], mode: inset }
