hvg_service_control:
    resource: "@HVGServiceControlBundle/Resources/config/routing.yml"
    prefix:   /servicecontrol

hvg_process:
    resource: "@HVGProcessBundle/Resources/config/routing.yml"
    prefix:   /process

hvg_configuration:
    resource: "@HVGConfigurationBundle/Resources/config/routing.yml"
    prefix:   /configuration

hvg_exchange:
    resource: "@HVGExchangeBundle/Resources/config/routing.yml"
    prefix:   /exchange

hvg_access_control:
    resource: "@HVGAccessControlBundle/Resources/config/routing.yml"
    prefix:   /accesscontrol

hvg_public:
    resource: "@HVGPublicBundle/Resources/config/routing.yml"
    prefix:   /public

hvg_contability:
    resource: "@HVGContabilityBundle/Resources/config/routing.yml"
    prefix:   /contability

hvg_agent:
    resource: "@HVGAgentBundle/Resources/config/routing.yml"
    prefix:   /agent

hvg_customer:
    resource: "@HVGCustomerBundle/Resources/config/routing.yml"
    prefix:   /customer

hvg_resource_planner:
    resource: "@HVGResourcePlannerBundle/Resources/config/routing.yml"
    prefix:   /resource

hvg_security:
    resource: "@HVGUserBundle/Resources/config/routing/security.yml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

fos_user:
    resource: "@HVGUserBundle/Resources/config/routing.yml"
    prefix:   /user

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

hvg_admin:
    resource: "@HVGAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

hvg_system:
    resource: "@HVGSystemBundle/Resources/config/routing.yml"
    prefix:   /system

root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /login
        permanent: true
