#Dashboard
hvg_system_dashboard:
    path:     /
    defaults: { _controller: HVGSystemBundle:Dashboard:index }

#Accounting
hvg_system_expenditure:
    resource: "@HVGSystemBundle/Resources/config/routing/expenditure.yml"
    prefix:   /expenditure

hvg_system_payment:
    resource: "@HVGSystemBundle/Resources/config/routing/payment.yml"
    prefix:   /payment

hvg_system_outflow:
    resource: "@HVGSystemBundle/Resources/config/routing/outflow.yml"
    prefix:   /outflow

hvg_system_inflow:
    resource: "@HVGSystemBundle/Resources/config/routing/inflow.yml"
    prefix:   /inflow

hvg_system_charge:
    resource: "@HVGSystemBundle/Resources/config/routing/charge.yml"
    prefix:   /charge

hvg_system_allowance:
    resource: "@HVGSystemBundle/Resources/config/routing/allowance.yml"
    prefix:   /allowance

hvg_system_allowancecharge:
    resource: "@HVGSystemBundle/Resources/config/routing/allowancecharge.yml"
    prefix:   /allowancecharge

#Human Resources
hvg_system_communitystaff:
    resource: "@HVGSystemBundle/Resources/config/routing/communitystaff.yml"
    prefix:   /communitystaff

hvg_system_role:
    resource: "@HVGSystemBundle/Resources/config/routing/role.yml"
    prefix:   /role

#Contacts
hvg_system_person:
    resource: "@HVGSystemBundle/Resources/config/routing/person.yml"
    prefix:   /person

hvg_system_contact:
    resource: "@HVGSystemBundle/Resources/config/routing/contact.yml"
    prefix:   /contact

hvg_system_contactkind:
    resource: "@HVGSystemBundle/Resources/config/routing/contactkind.yml"
    prefix:   /contactkind

#Configuration
hvg_system_personprovider: 
    resource: "@HVGSystemBundle/Resources/config/routing/personprovider.yml"
    prefix:   /personprovider  

hvg_system_result:
    resource: "@HVGSystemBundle/Resources/config/routing/result.yml"
    prefix:   /result

hvg_system_bank:
    resource: "@HVGSystemBundle/Resources/config/routing/bank.yml"
    prefix:   /bank

hvg_system_bankaccount:
    resource: "@HVGSystemBundle/Resources/config/routing/bankaccount.yml"
    prefix:   /bankaccount

hvg_system_bankaccountkind:
    resource: "@HVGSystemBundle/Resources/config/routing/bankaccountkind.yml"
    prefix:   /bankaccountkind    

hvg_system_area:
    resource: "@HVGSystemBundle/Resources/config/routing/area.yml"
    prefix:   /area

hvg_system_unit:
    resource: "@HVGSystemBundle/Resources/config/routing/unit.yml"
    prefix:   /unit

hvg_system_unitgroup:
    resource: "@HVGSystemBundle/Resources/config/routing/unitgroup.yml"
    prefix:   /unitgroup

hvg_system_community:
    resource: "@HVGSystemBundle/Resources/config/routing/community.yml"
    prefix:   /community

hvg_system_service:
    resource: "@HVGSystemBundle/Resources/config/routing/service.yml"
    prefix:   /service

hvg_system_fund:
    resource: "@HVGSystemBundle/Resources/config/routing/fund.yml"
    prefix:   /fund

hvg_system_provider:
    resource: "@HVGSystemBundle/Resources/config/routing/provider.yml"
    prefix:   /provider

#Tickets
hvg_system_ticketstatus:
    resource: "@HVGSystemBundle/Resources/config/routing/ticketstatus.yml"
    prefix:   /ticketstatus

hvg_system_ticketaction:
    resource: "@HVGSystemBundle/Resources/config/routing/ticketaction.yml"
    prefix:   /ticketaction

hvg_system_ticket:
    resource: "@HVGSystemBundle/Resources/config/routing/ticket.yml"
    prefix:   /ticket

#Request
hvg_system_petitionevaluation:
    resource: "@HVGSystemBundle/Resources/config/routing/petitionevaluation.yml"
    prefix:   /petitionevaluation

hvg_system_petitionstatus:
    resource: "@HVGSystemBundle/Resources/config/routing/petitionstatus.yml"
    prefix:   /petitionstatus

hvg_system_petitionaction:
    resource: "@HVGSystemBundle/Resources/config/routing/petitionaction.yml"
    prefix:   /petitionaction

hvg_system_petition:
    resource: "@HVGSystemBundle/Resources/config/routing/petition.yml"
    prefix:   /petition

#Projects
hvg_system_projectproposal:
    resource: "@HVGSystemBundle/Resources/config/routing/projectproposal.yml"
    prefix:   /projectproposal

hvg_system_projectstatus:
    resource: "@HVGSystemBundle/Resources/config/routing/projectstatus.yml"
    prefix:   /projectstatus

hvg_system_projectaction:
    resource: "@HVGSystemBundle/Resources/config/routing/projectaction.yml"
    prefix:   /projectaction

hvg_system_projectcommand:
    resource: "@HVGSystemBundle/Resources/config/routing/projectcommand.yml"
    prefix:   /projectcommand

hvg_system_projectobservation:
    resource: "@HVGSystemBundle/Resources/config/routing/projectobservation.yml"
    prefix:   /projectobservation

hvg_system_project:
    resource: "@HVGSystemBundle/Resources/config/routing/project.yml"
    prefix:   /project

#Testing
hvg_system_testing:
    resource: "@HVGSystemBundle/Resources/config/routing/testing.yml"
    prefix:   /testing

hvg_system_homepage:
    path:     /
    defaults: { _controller: HVGSystemBundle:Default:index }
