hvg_agent_dashboard:
    resource: "@HVGAgentBundle/Resources/config/routing/dashboard.yml"
    prefix:   /

hvg_agent_datacenter:
    resource: "@HVGAgentBundle/Resources/config/routing/datacenter.yml"
    prefix:   /datacenter

hvg_agent_unitgroup:
    resource: "@HVGAgentBundle/Resources/config/routing/unitgroup.yml"
    prefix:   /unitgroup

hvg_agent_unitlog:
    resource: "@HVGAgentBundle/Resources/config/routing/unitlog.yml"
    prefix:   /unitlog

hvg_agent_unitmemo:
    resource: "@HVGAgentBundle/Resources/config/routing/unitmemo.yml"
    prefix:   /unitmemo

hvg_agent_unitresident:
    resource: "@HVGAgentBundle/Resources/config/routing/unitresident.yml"
    prefix:   /unitresident

hvg_agent_warehouse:
    resource: "@HVGAgentBundle/Resources/config/routing/warehouse.yml"
    prefix:   /warehouse

hvg_agent_carpark:
    resource: "@HVGAgentBundle/Resources/config/routing/carpark.yml"
    prefix:   /carpark

hvg_agent_guest:
    resource: "@HVGAgentBundle/Resources/config/routing/guest.yml"
    prefix:   /guest

hvg_agent_community:
    resource: "@HVGAgentBundle/Resources/config/routing/community.yml"
    prefix:   /community

hvg_agent_communitystaff:
    resource: "@HVGAgentBundle/Resources/config/routing/communitystaff.yml"
    prefix:   /communitystaff

hvg_agent_contact:
    resource: "@HVGAgentBundle/Resources/config/routing/contact.yml"
    prefix:   /contact

hvg_agent_person:
    resource: "@HVGAgentBundle/Resources/config/routing/person.yml"
    prefix:   /person

hvg_agent_provider:
    resource: "@HVGAgentBundle/Resources/config/routing/provider.yml"
    prefix:   /provider

hvg_agent_unit:
    resource: "@HVGAgentBundle/Resources/config/routing/unit.yml"
    prefix:   /unit

hvg_agent_unitinsurancepolicy:
    resource: "@HVGAgentBundle/Resources/config/routing/unitinsurancepolicy.yml"
    prefix:   /unitinsurancepolicy

hvg_agent_ticket:
    resource: "@HVGAgentBundle/Resources/config/routing/ticket.yml"
    prefix:   /ticket

hvg_agent_ticketaction:
    resource: "@HVGAgentBundle/Resources/config/routing/ticketaction.yml"
    prefix:   /ticketaction

hvg_agent_petition:
    resource: "@HVGAgentBundle/Resources/config/routing/petition.yml"
    prefix:   /petition

hvg_agent_petitionaction:
    resource: "@HVGAgentBundle/Resources/config/routing/petitionaction.yml"
    prefix:   /petitionaction

hvg_agent_expenditure:
    resource: "@HVGAgentBundle/Resources/config/routing/expenditure.yml"
    prefix:   /expenditure

hvg_agent_outflow:
    resource: "@HVGAgentBundle/Resources/config/routing/outflow.yml"
    prefix:   /outflow

hvg_agent_error:
    resource: "@HVGAgentBundle/Resources/config/routing/error.yml"
    prefix:   /error
