agent_petitionaction_index:
    path:     /
    defaults: { _controller: "HVGAgentBundle:PetitionAction:index" }
    methods:  GET

agent_petitionaction_show:
    path:     /{id}/show
    defaults: { _controller: "HVGAgentBundle:PetitionAction:show" }
    methods:  GET

agent_petitionaction_new:
    path:     /new
    defaults: { _controller: "HVGAgentBundle:PetitionAction:new" }
    methods:  [GET, POST]
