agent_petition_index:
    path:     /index
    defaults: { _controller: "HVGAgentBundle:Petition:index" }
    methods:  GET

agent_petition_show:
    path:     /{id}/show
    defaults: { _controller: "HVGAgentBundle:Petition:show" }
    methods:  GET

agent_petition_new:
    path:     /new
    defaults: { _controller: "HVGAgentBundle:Petition:new" }
    methods:  [GET, POST]

agent_petition_status:
    path:     /{id}/status
    defaults: { _controller: "HVGAgentBundle:Petition:status" }
    methods:  [GET, POST]

agent_petition_addreference:
    path:     /{id}/addreference
    defaults: { _controller: "HVGAgentBundle:Petition:addreference" }
    methods:  [GET, POST]

agent_petition_removereference:
    path:     /{id}/removereference
    defaults: { _controller: "HVGAgentBundle:Petition:removereference" }
    methods:  [GET]

agent_petition_edit:
    path:     /{id}/edit
    defaults: { _controller: "HVGAgentBundle:Petition:edit" }
    methods:  [GET, POST]

agent_petition_completeobjective:
    path:     /{id}/completeobjective
    defaults: { _controller: "HVGAgentBundle:Petition:completeObjective" }
    methods:  GET

agent_petition_restartobjective:
    path:     /{id}/restartobjective
    defaults: { _controller: "HVGAgentBundle:Petition:restartObjective" }
    methods:  GET

agent_petition_my:
    path:     /my
    defaults: { _controller: "HVGAgentBundle:Petition:my" }
    methods:  GET

