agent_ticket_index:
    path:     /index
    defaults: { _controller: "HVGAgentBundle:Ticket:index" }
    methods:  GET

agent_ticket_show:
    path:     /{id}/show
    defaults: { _controller: "HVGAgentBundle:Ticket:show" }
    methods:  GET

agent_ticket_new:
    path:     /new
    defaults: { _controller: "HVGAgentBundle:Ticket:new" }
    methods:  [GET, POST]

agent_ticket_status:
    path:     /{id}/status
    defaults: { _controller: "HVGAgentBundle:Ticket:status" }
    methods:  [GET, POST]

agent_ticket_edit:
    path:     /{id}/edit
    defaults: { _controller: "HVGAgentBundle:Ticket:edit" }
    methods:  [GET, POST]

agent_ticket_filter:
    path:     /filter
    defaults: { _controller: "HVGAgentBundle:Ticket:filter" }
    methods:  [GET, POST]

agent_ticket_search:
    path:     /search
    defaults: { _controller: "HVGAgentBundle:Ticket:search" }
    methods:  [GET, POST]

agent_ticket_my:
    path:     /my
    defaults: { _controller: "HVGAgentBundle:Ticket:my" }
    methods:  GET

