agent_ticketaction_index:
    path:     /
    defaults: { _controller: "HVGAgentBundle:TicketAction:index" }
    methods:  GET

agent_ticketaction_show:
    path:     /{id}/show
    defaults: { _controller: "HVGAgentBundle:TicketAction:show" }
    methods:  GET

agent_ticketaction_new:
    path:     /new
    defaults: { _controller: "HVGAgentBundle:TicketAction:new" }
    methods:  [GET, POST]

agent_ticketaction_getfile:
    path:     /{id}/getfile
    defaults: { _controller: "HVGAgentBundle:TicketAction:getfile" }
    methods:  GET
