agent_unit_index:
    path:     /
    defaults: { _controller: "HVGAgentBundle:Unit:index" }
    methods:  GET

agent_unit_show:
    path:     /{id}/show
    defaults: { _controller: "HVGAgentBundle:Unit:show" }
    methods:  GET

agent_unit_unitgroup:
    path:     /{id}/unitgroup
    defaults: { _controller: "HVGAgentBundle:Unit:unitgroup" }
    methods:  GET
